from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import io
import datetime

def generate_pdf_report(user_stats, filename="Analytics_Report.pdf"):
    """
    Generates a PDF using reportlab with the given analytics
    user_stats: dict containing most_searched, total_saved, etc.
    """
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    c.setFont("Helvetica-Bold", 20)
    c.drawString(50, height - 50, "Monthly Price Intelligence Report")

    c.setFont("Helvetica", 14)
    y_pos = height - 100
    c.drawString(50, y_pos, f"Date: {datetime.date.today().strftime('%B %d, %Y')}")

    y_pos -= 40
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y_pos, "Your Analytics Summary")
    
    y_pos -= 30
    c.setFont("Helvetica", 12)
    
    for key, val in user_stats.items():
        text = f"{key.replace('_', ' ').title()}: {val}"
        c.drawString(50, y_pos, text)
        y_pos -= 20

    # Draw a line
    c.line(50, y_pos - 10, width - 50, y_pos - 10)
    
    y_pos -= 40
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, y_pos, "Generated by Price Intelligence AI Platform")

    c.save()
    buffer.seek(0)
    return buffer
